"use strict";
const UI=window.HomeEnergyUI;
const {$,t,stampLabel,localInput,displayDateTime,periodFromUrl,periodQuery,writePeriodUrl,PeriodNavigator,api,writeStorage,socState}=UI;
const NS="http://www.w3.org/2000/svg";
const IDLE_MS=UI.IDLE_MS,ACTIVITY_KEY=UI.ACTIVITY_KEY,LOGOUT_KEY=UI.LOGOUT_KEY;
const metricColors={pv_power_kw:"#f6c453",load_power_kw:"#77aaff",grid_import_power_kw:"#fb9090",grid_export_power_kw:"#58d8b5",battery_charge_power_kw:"#63cfe4",battery_discharge_power_kw:"#bc9dff",battery_soc_pct:"#a4d982"};
const groups=[
  {titleKey:"group.solarLoad",metrics:["pv_power_kw","load_power_kw"],unit:"kW"},
  {titleKey:"group.grid",metrics:["grid_import_power_kw","grid_export_power_kw"],unit:"kW"},
  {titleKey:"group.batteryPower",metrics:["battery_charge_power_kw","battery_discharge_power_kw"],unit:"kW"},
  {titleKey:"group.soc",metrics:["battery_soc_pct"],unit:"%"}
];
const controllers=new Set();
let historyData=null,currentData=null,charts=[],active=false,busy=false,generation=0,refreshTimer=null,idleTimer=null,activityTimer=null;
let lastHuman=0,lastActivitySent=0,lastStorageWrite=0,activityBusy=false,resizeFrame=null;
let selectedPeriod=periodFromUrl(),selected=periodQuery(selectedPeriod);
let hiddenMetrics=new Set();
try{hiddenMetrics=new Set(JSON.parse(localStorage.getItem("home-energy-v2-hidden")||"[]").filter(metric=>metricColors[metric]));}catch{}

function svg(tag,attrs={},text){const node=document.createElementNS(NS,tag);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,String(value));if(text!==undefined)node.textContent=text;return node;}
function valueLabel(value,unit){return typeof value==="number"&&Number.isFinite(value)?value.toFixed(unit==="%"?1:2):"—";}
function setAuthView(view,message=""){$("auth-loading").hidden=view!=="loading";$(`login`).hidden=view!=="login";$(`dashboard`).hidden=view!=="app";if(view==="loading"&&message){const text=$("auth-loading").querySelector("div");text.textContent=message;}if(view==="login"){$("login-error").textContent=message;$(`password`).value="";}}
async function request(path,options={}){return api(path,controllers,options);}
function showLogin(message=""){
  generation++;active=false;busy=false;activityBusy=false;clearTimeout(refreshTimer);clearTimeout(activityTimer);clearInterval(idleTimer);refreshTimer=activityTimer=idleTimer=null;for(const controller of controllers)controller.abort();controllers.clear();
  setAuthView("login",message);$("mode").hidden=true;$("logout").hidden=true;historyData=currentData=null;charts=[];$("latest").replaceChildren();$("charts").replaceChildren();$("refresh").disabled=false;
}
function showAuthError(message){setAuthView("loading",message);$("auth-loading").querySelector(".spinner").hidden=true;}
function startSession(session){active=true;generation++;lastHuman=session.last_activity*1000;$("auth-loading").querySelector(".spinner").hidden=false;setAuthView("app");$("mode").hidden=false;$("logout").hidden=false;idleTimer=setInterval(checkIdle,1000);if(!charts.length)buildCharts();$("range-label").textContent=rangeText();refresh(true,true);}
async function logout(message="",broadcast=true){showLogin(message);if(broadcast)writeStorage(LOGOUT_KEY,Date.now());try{await request("/api/logout",{method:"POST",body:"{}"});}catch{}}
function checkIdle(){if(!active)return true;if(Date.now()-lastHuman>=IDLE_MS){logout(t("auth.idle"));return true;}return false;}
function humanActivity(event){if(!active||!event.isTrusted)return;if(checkIdle())return;lastHuman=Date.now();if(lastHuman-lastStorageWrite>1000){writeStorage(ACTIVITY_KEY,lastHuman);lastStorageWrite=lastHuman;}if(!activityTimer&&!activityBusy)activityTimer=setTimeout(sendActivity,Math.max(0,30000-(Date.now()-lastActivitySent)));}
async function sendActivity(){activityTimer=null;if(!active||activityBusy||checkIdle())return;const idle=(Date.now()-lastHuman)/1000;if(idle>60)return;activityBusy=true;lastActivitySent=Date.now();const ticket=generation;try{await request("/api/activity",{method:"POST",body:JSON.stringify({idle_seconds:Math.max(0,idle)})});}catch(error){if(ticket===generation&&error.status===401)showLogin(error.message);}finally{if(ticket===generation)activityBusy=false;}}
function scheduleRefresh(){clearTimeout(refreshTimer);if(active&&!document.hidden)refreshTimer=setTimeout(()=>refresh(false,true),60000);$("refresh-state").textContent=t(document.hidden?"status.paused":"status.auto");}

function renderStats(){if(!currentData)return;$("latest").replaceChildren();for(const metric of ["pv_power_kw","load_power_kw","grid_import_power_kw","battery_soc_pct"]){const point=currentData.latest?.[metric],unit=metric.endsWith("pct")?"%":"kW",card=document.createElement("article");card.className="stat";const label=document.createElement("div");label.className="label";label.textContent=t(`metric.${metric}`);const value=document.createElement("div");value.className="value";value.textContent=valueLabel(point?.value,unit);const state=metric==="battery_soc_pct"?socState(Number(point?.value)):null;if(state)value.classList.add(state.className);const suffix=document.createElement("span");suffix.className="unit";suffix.textContent=unit;value.append(suffix);const time=document.createElement("div");time.className="time";const old=!point||Date.now()-point.t>900000;time.textContent=point?`${t("status.sampleAt",{time:stampLabel(point.t,true)})}${old?` · ${t("status.stale")}`:""}`:t("status.waiting");card.classList.toggle("old",old);card.append(label,value,time);if(state){const status=document.createElement("div");status.className=`soc-label ${state.className}`;status.textContent=state.label;card.append(status);}$("latest").append(card);}}
function niceMax(value){if(!(value>0))return 1;const scale=10**Math.floor(Math.log10(value));return [1,2,2.5,5,10].map(item=>item*scale).find(item=>item>=value)||10*scale;}
function tickLabel(value,step,unit){const digits=step>=1?(Math.abs(value-Math.round(value))<1e-8?0:1):step>=.1?1:2;return `${Number(value.toFixed(digits))} ${unit}`;}
function nearest(points,target,tolerance=Infinity){let low=0,high=points.length;while(low<high){const middle=(low+high)>>1;if(points[middle][0]<target)low=middle+1;else high=middle;}const point=[points[low-1],points[low]].filter(Boolean).sort((a,b)=>Math.abs(a[0]-target)-Math.abs(b[0]-target))[0];return point&&Math.abs(point[0]-target)<=tolerance?point:null;}
function reduceSegment(points,buckets,start,end){if(points.length<buckets*4)return points;const result=[];let group=[],bin=-1;function flush(){if(!group.length)return;const minimum=group.reduce((a,b)=>a[1]<b[1]?a:b),maximum=group.reduce((a,b)=>a[1]>b[1]?a:b);result.push(...[...new Set([group[0],minimum,maximum,group[group.length-1]])].sort((a,b)=>a[0]-b[0]));group=[];}for(const point of points){const next=Math.floor((point[0]-start)/(end-start)*buckets);if(next!==bin){flush();bin=next;}group.push(point);}flush();return result;}
function draw(chart){
  if(!historyData){chart.loading.hidden=false;chart.canvas.classList.add("is-loading");return;}if(chart.plot.clientWidth<1)return;chart.loading.hidden=true;chart.canvas.classList.remove("is-loading");
  const {group,plot,canvas,tip}=chart,width=plot.clientWidth,height=plot.clientHeight,left=58,right=14,top=12,bottom=35,w=width-left-right,h=height-top-bottom;
  const [start,end]=chart.zoom||[historyData.range.start_ms,historyData.range.end_ms];
  const rows=group.metrics.filter(metric=>!hiddenMetrics.has(metric)).map(metric=>({metric,points:(historyData.series?.find(row=>row.metric===metric)?.points||[]).filter(point=>point[0]>=start&&point[0]<end)}));
  let maximum=0,valid=0;for(const row of rows)for(const point of row.points)if(point[1]!==null){maximum=Math.max(maximum,point[1]);valid++;}
  const ymax=group.unit==="%"?100:niceMax(maximum*1.08),step=ymax/4,x=time=>left+(time-start)/(end-start)*w,y=value=>top+h-value/ymax*h;
  canvas.replaceChildren();canvas.setAttribute("viewBox",`0 0 ${width} ${height}`);
  for(let index=0;index<=4;index++){const value=step*index,yy=y(value);canvas.append(svg("line",{x1:left,y1:yy,x2:width-right,y2:yy,stroke:"#28364c"}),svg("text",{x:left-8,y:yy+4,"text-anchor":"end",fill:"#91a8c7","font-size":11},tickLabel(value,step,group.unit)));}
  const count=width<450?3:5,long=end-start>36*3600000,axisFormatter=new Intl.DateTimeFormat(UI.locale(),{timeZone:UI.ZONE,...(long?{day:"2-digit",month:"short"}:{hour:"2-digit",minute:"2-digit",hourCycle:"h23"})});
  for(let index=0;index<count;index++){const time=start+index/(count-1)*(end-start),shown=Math.min(time,end-1);canvas.append(svg("text",{x:x(time),y:height-9,"text-anchor":index===0?"start":index===count-1?"end":"middle",fill:"#91a8c7","font-size":11},axisFormatter.format(new Date(shown))));}
  for(const row of rows){let segment=[],segments=[];for(const point of row.points){if(point[1]===null){if(segment.length)segments.push(segment);segment=[];continue;}if(segment.length&&point[0]-segment[segment.length-1][0]>historyData.max_gap_seconds*1000){segments.push(segment);segment=[];}segment.push(point);}if(segment.length)segments.push(segment);let path="";for(const values of segments){const shown=reduceSegment(values,Math.max(1,Math.floor(w)),start,end);path+=shown.map((point,index)=>`${index?"L":"M"}${x(point[0]).toFixed(2)},${y(point[1]).toFixed(2)}`).join(" ")+" ";if(shown.length===1)canvas.append(svg("circle",{cx:x(shown[0][0]),cy:y(shown[0][1]),r:2,fill:metricColors[row.metric]}));}canvas.append(svg("path",{d:path,fill:"none",stroke:metricColors[row.metric],"stroke-width":1.3,"stroke-linejoin":"round","stroke-linecap":"round","data-series":row.metric}));}
  if(!valid)canvas.append(svg("text",{x:width/2,y:height/2,"text-anchor":"middle",fill:"#91a8c7","font-size":13},t(rows.length?"chart.empty":"chart.select")));
  const selection=svg("rect",{x:0,y:top,width:0,height:h,fill:"#83d5bc24",stroke:"#83d5bc",visibility:"hidden"}),guide=svg("line",{class:"guide",x1:0,x2:0,y1:top,y2:top+h,visibility:"hidden"}),markers=svg("g",{visibility:"hidden"});canvas.append(selection,guide,markers);
  const validTimes=[...new Set(rows.flatMap(row=>row.points.filter(point=>point[1]!==null).map(point=>point[0])))].sort((a,b)=>a-b),timePoints=validTimes.map(time=>[time,time]);
  const px=event=>Math.max(left,Math.min(width-right,event.clientX-plot.getBoundingClientRect().left)),toTime=position=>start+(position-left)/w*(end-start),tolerance=Math.max(10*60000,(end-start)/Math.max(w,1)*18);
  const targetAt=position=>nearest(timePoints,toTime(position),tolerance)?.[0]??null;
  function defaultHint(){chart.hint.classList.remove("selecting");chart.hint.textContent=chart.zoom?`${stampLabel(start,true)} — ${stampLabel(end,true)}`:t(matchMedia("(pointer:coarse)").matches?"chart.touchHint":"chart.desktopHint");}
  function hideTooltip(){tip.hidden=true;tip.classList.remove("pinned");guide.setAttribute("visibility","hidden");markers.replaceChildren();markers.setAttribute("visibility","hidden");}
  function showTooltip(position,clientY=null,pinned=false,targetOverride=null){const target=targetOverride??targetAt(position);if(target===null||target<start||target>=end){hideTooltip();return false;}const lines=[stampLabel(target,true)];let readings=0;markers.replaceChildren();for(const row of rows){const point=nearest(row.points,target,5*60000);if(point&&point[1]!==null){readings++;lines.push(`${t(`metric.${row.metric}`)}: ${valueLabel(point[1],group.unit)} ${group.unit}`);markers.append(svg("circle",{cx:x(target),cy:y(point[1]),r:3.2,fill:metricColors[row.metric],stroke:"#0b1220","stroke-width":1.2}));}}if(!readings){hideTooltip();return false;}const marker=x(target);tip.textContent=lines.join("\n");tip.hidden=false;tip.classList.toggle("pinned",pinned);tip.dataset.timestamp=String(target);guide.setAttribute("x1",marker);guide.setAttribute("x2",marker);guide.setAttribute("visibility","visible");markers.setAttribute("visibility","visible");tip.style.left=`${Math.max(2,Math.min(width-tip.offsetWidth-2,marker+10))}px`;const rect=plot.getBoundingClientRect();tip.style.top=clientY!==null&&clientY-rect.top<height/2?`${Math.max(8,height-tip.offsetHeight-12)}px`:"8px";return true;}
  function showSelection(first,position){const a=Math.min(first,position),b=Math.max(first,position);selection.setAttribute("x",a);selection.setAttribute("width",Math.max(0,b-a));selection.setAttribute("visibility",Math.abs(b-a)>=3?"visible":"hidden");chart.hint.classList.add("selecting");chart.hint.textContent=t("chart.zooming",{start:stampLabel(toTime(a),true),end:stampLabel(toTime(b),true)});}
  plot.onpointerdown=event=>{if(event.button!==0)return;const position=px(event);chart.pointer={start:position,last:position,startY:event.clientY,id:event.pointerId,type:event.pointerType,gesture:event.pointerType==="mouse"?"horizontal":"pending"};if(event.pointerType==="mouse"){chart.drag={start:position,id:event.pointerId};tip.hidden=true;plot.setPointerCapture(event.pointerId);}};
  plot.onpointermove=event=>{const pointer=chart.pointer,position=px(event);if(pointer&&pointer.id===event.pointerId){pointer.last=position;const dx=position-pointer.start,dy=event.clientY-pointer.startY;if(pointer.type!=="mouse"&&pointer.gesture==="pending"&&(Math.abs(dx)>8||Math.abs(dy)>8)){if(Math.abs(dx)>Math.abs(dy)*1.15){pointer.gesture="horizontal";plot.setPointerCapture(event.pointerId);}else if(Math.abs(dy)>Math.abs(dx)*1.05){pointer.gesture="vertical";chart.pointer=null;return;}}if(pointer.type!=="mouse"&&pointer.gesture==="horizontal"){event.preventDefault();showTooltip(position,event.clientY,false);if(Math.abs(dx)>=28)showSelection(pointer.start,position);return;}}if(chart.drag){showSelection(chart.drag.start,position);return;}if(event.pointerType==="mouse"&&!chart.pinned)showTooltip(position,event.clientY,false);};
  plot.onpointerup=event=>{const pointer=chart.pointer,reported=px(event),position=event.pointerType==="mouse"?reported:(pointer?.last??reported);chart.pointer=null;if(plot.hasPointerCapture(event.pointerId))plot.releasePointerCapture(event.pointerId);if(event.pointerType==="mouse"){if(!chart.drag)return;const first=chart.drag.start;chart.drag=null;if(Math.abs(first-position)>=10){const a=toTime(Math.min(first,position)),b=toTime(Math.max(first,position));if(b-a>=60000){chart.zoom=[a,b];chart.pinned=null;}}draw(chart);return;}if(!pointer||pointer.gesture==="vertical")return;const dx=position-pointer.start,dy=(Number.isFinite(event.clientY)?event.clientY:pointer.startY)-pointer.startY;if(pointer.gesture==="horizontal"&&Math.abs(dx)>=32){const a=toTime(Math.min(pointer.start,position)),b=toTime(Math.max(pointer.start,position));if(b-a>=60000){chart.zoom=[a,b];chart.pinned=null;}draw(chart);return;}if(Math.abs(dx)<=18&&Math.abs(dy)<=18||pointer.gesture==="horizontal"){const target=targetAt(position);chart.pinned=target===null||chart.pinned===target?null:target;draw(chart);}};
  plot.onpointercancel=()=>{chart.drag=null;chart.pointer=null;draw(chart);};plot.onpointerleave=event=>{if(event.pointerType==="mouse"&&!chart.drag&&!chart.pinned)hideTooltip();};plot.ondblclick=()=>{if(matchMedia("(hover:hover) and (pointer:fine)").matches){chart.zoom=null;chart.drag=null;chart.pinned=null;draw(chart);}};
  chart.reset.hidden=!chart.zoom;defaultHint();canvas.dataset.start=String(start);canvas.dataset.end=String(end);if(chart.pinned){if(!showTooltip(x(chart.pinned),null,true,chart.pinned))chart.pinned=null;}else hideTooltip();
}
function buildCharts(){charts=[];$("charts").replaceChildren();for(const group of groups){const card=document.createElement("section");card.className="chart-card";const head=document.createElement("div");head.className="chart-head";const title=document.createElement("h2");title.textContent=t(group.titleKey);const actions=document.createElement("div");actions.className="chart-actions";const reset=UI.createButton(t("chart.reset"),"reset");reset.hidden=true;actions.append(reset);head.append(title,actions);const legend=document.createElement("div");legend.className="legend";for(const metric of group.metrics){const label=document.createElement("label"),input=document.createElement("input"),caption=document.createElement("span");input.type="checkbox";input.checked=!hiddenMetrics.has(metric);input.dataset.metric=metric;caption.dataset.metricLabel=metric;caption.textContent=t(`metric.${metric}`);label.style.setProperty("--color",metricColors[metric]);label.classList.toggle("off",!input.checked);label.append(input,caption);input.onchange=()=>{input.checked?hiddenMetrics.delete(metric):hiddenMetrics.add(metric);label.classList.toggle("off",!input.checked);writeStorage("home-energy-v2-hidden",JSON.stringify([...hiddenMetrics]));charts.forEach(draw);};legend.append(label);}const plot=document.createElement("div");plot.className="plot";const canvas=svg("svg",{role:"img","aria-label":`${t(group.titleKey)}, ${group.unit}`}),tip=document.createElement("div"),loading=document.createElement("div");tip.className="tip";tip.hidden=true;loading.className="chart-loading";loading.innerHTML='<span></span><span></span><span></span>';const hint=document.createElement("div");hint.className="chart-hint";plot.append(canvas,tip,loading);card.append(head,legend,plot,hint);$("charts").append(card);const chart={group,title,plot,canvas,tip,loading,hint,reset,zoom:null,drag:null,pointer:null,pinned:null};reset.onclick=()=>{chart.zoom=null;chart.drag=null;chart.pinned=null;draw(chart);};charts.push(chart);draw(chart);}}
function updateChartLanguage(){for(const chart of charts){chart.title.textContent=t(chart.group.titleKey);chart.reset.textContent=t("chart.reset");chart.canvas.setAttribute("aria-label",`${t(chart.group.titleKey)}, ${chart.group.unit}`);chart.plot.querySelectorAll("[data-metric-label]").forEach(node=>node.textContent=t(`metric.${node.dataset.metricLabel}`));draw(chart);}}
function rangeText(){if(selectedPeriod.mode==="other")return `${displayDateTime(selectedPeriod.fromDate,selectedPeriod.fromTime)} — ${displayDateTime(selectedPeriod.toDate,selectedPeriod.toTime)} · ${t("range.melbourne")}`;const finish=localInput(selectedPeriod.endMs-1).date;return `${displayDateTime(selectedPeriod.fromDate,"00:00")} — ${displayDateTime(finish,"23:59")} · ${t("range.melbourne")}`;}
function fastEligible(){return ["day","week","month"].includes(selectedPeriod.mode);}
function fastResolution(data){if(!data)return "";if(data.resolution==="5s_raw")return t("status.resolutionSeconds",{value:5});if(data.resolution_seconds>=60&&data.resolution_seconds%60===0)return t("status.resolutionMinutes",{value:data.resolution_seconds/60});return t("status.resolutionSeconds",{value:data.resolution_seconds||5});}
async function readFastTelemetry(){if(!fastEligible())return null;const params=new URLSearchParams(selected);params.set("source","foxess_ws");params.set("resolution","auto");try{return (await request("/api/telemetry/history?"+params)).data;}catch(error){if(error.status===401)throw error;return {available:false,reason:"request_failed",error};}}
function renderHistory(manual,previousLatest){if(!historyData)return;const messages=[...(historyData.warnings||[])];if(historyData.collector.catching_up)messages.push(t("status.catchingUp"));if(historyData.collector.backfill_active)messages.push(t("status.backfill"));$("banner").textContent=messages.join("\n");$("banner").hidden=!messages.length;$("read-time").textContent=t("status.readAt",{time:stampLabel(historyData.checked_at,true)});$("sync-time").textContent=t("status.syncedAt",{time:stampLabel(historyData.collector.last_success_at,true)});$("range-label").textContent=rangeText();const fast=historyData.fast_telemetry,$source=$("history-source");$source.textContent=fast?.available?t("status.fastSource",{resolution:fastResolution(fast)}):t("status.restSource");$source.classList.toggle("is-stale",Boolean(fast?.available&&!fast.collector?.healthy));$source.title=fast?.available&&!fast.collector?.healthy?t("status.fastUnhealthy"):"";$("status").textContent=manual?(previousLatest&&previousLatest===currentData?.latest_observed_at?t("status.noNewSample"):t("status.reloaded")):t("status.checked");$("collector-status").textContent=t("status.collector",{minutes:historyData.collector.cadence_seconds/60,calls:historyData.collector.calls_last_24h,budget:historyData.collector.budget});if(!charts.length)buildCharts();charts.forEach(draw);}
async function refresh(manual=false,updateCurrent=true){
  if(!active||checkIdle()||busy)return;busy=true;clearTimeout(refreshTimer);$("refresh").disabled=true;$("refresh").textContent=t("common.loading");$("status").textContent=t("status.readingHistory");const ticket=generation,previousLatest=currentData?.latest_observed_at,params=new URLSearchParams(selected);if(manual)params.set("force","1");if(historyData&&!manual){params.set("known_revision",historyData.revision);params.set("known_range",historyData.range.key);}
  try{const result=(await request("/api/history?"+params)).data;if(ticket!==generation||!active)return;if(historyData&&result.range.key!==historyData.range.key)for(const chart of charts){chart.zoom=null;chart.pinned=null;}let next=result.not_modified&&historyData?{...historyData,...result,series:historyData.series}:result;if(updateCurrent){currentData=result;renderStats();}const fast=await readFastTelemetry();if(ticket!==generation||!active)return;if(fast?.available&&fast.series?.some(row=>row.points?.length))next={...next,series:fast.series,max_gap_seconds:fast.max_gap_seconds,checked_at:fast.checked_at,fast_telemetry:fast};else next={...next,fast_telemetry:fast};historyData=next;renderHistory(manual,previousLatest);}
  catch(error){if(ticket!==generation)return;if(error.status===401){showLogin(error.message);return;}$("banner").hidden=false;$("banner").textContent=(error.name==="AbortError"?t("status.timeout"):error.message)+(historyData?`\n${t("status.keepChart")}`:"");$("status").textContent=t("status.failed");}
  finally{if(ticket===generation){busy=false;$("refresh").disabled=false;$("refresh").textContent=t("common.refresh");scheduleRefresh();}}
}
function updateNavLink(){$("daily-link").href="/daily"+location.search;}
function changePeriod(period){generation++;for(const controller of controllers)controller.abort();controllers.clear();busy=false;activityBusy=false;selectedPeriod=period;selected=periodQuery(period);historyData=null;buildCharts();$("range-label").textContent=rangeText();updateNavLink();if(active)refresh(true,false);}

selectedPeriod.label=UI.periodLabel(selectedPeriod);writePeriodUrl(selectedPeriod,true);updateNavLink();
const periodNavigator=new PeriodNavigator(selectedPeriod,changePeriod);
$("login-form").addEventListener("submit",async event=>{event.preventDefault();$("login-button").disabled=true;$("login-error").textContent="";try{const session=await request("/api/login",{method:"POST",body:JSON.stringify({password:$("password").value})});$("password").value="";writeStorage(ACTIVITY_KEY,session.last_activity*1000);startSession(session);}catch(error){$("login-error").textContent=error.message;}finally{$("login-button").disabled=false;}});
$("refresh").onclick=()=>refresh(true,true);$("logout").onclick=()=>logout();
for(const name of ["pointerdown","pointermove","keydown","wheel","touchstart"])document.addEventListener(name,humanActivity,{passive:true});
window.addEventListener("storage",event=>{if(!active)return;if(event.key===LOGOUT_KEY){showLogin(t("auth.otherTab"));return;}if(event.key===ACTIVITY_KEY){const stamp=Number(event.newValue);if(stamp<=Date.now()+1000)lastHuman=Math.max(lastHuman,stamp);}});
window.addEventListener("popstate",()=>{const period=periodFromUrl();periodNavigator.setCurrent(period);changePeriod(period);});
document.addEventListener("visibilitychange",()=>{if(!active)return;if(checkIdle())return;if(document.hidden){clearTimeout(refreshTimer);clearTimeout(activityTimer);activityTimer=null;sendActivity();scheduleRefresh();}else refresh(false,true);});
window.addEventListener("pageshow",()=>{if(active&&!checkIdle())refresh(false,true);});window.addEventListener("resize",()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>charts.forEach(draw));});
window.addEventListener("languagechange",()=>{updateNavLink();if(currentData)renderStats();if(historyData)renderHistory(false,currentData?.latest_observed_at);updateChartLanguage();scheduleRefresh();});
(async()=>{try{startSession(await request("/api/session"));}catch(error){if(error.status===401)showLogin("");else showAuthError(error.message);}})();
